/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['<rootDir>/tests/**/*.spec.ts', '<rootDir>/tests/**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@config$': '<rootDir>/src/config/index',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@repositories/(.*)$': '<rootDir>/src/repositories/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@utils/(.*)$': '<rootDir>/src/shared/utils/$1',
    '^@utils$': '<rootDir>/src/shared/utils/index',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@shared$': '<rootDir>/src/shared/index',
    '^@verification/(.*)$': '<rootDir>/src/shared/verification/$1',
    '^@verification$': '<rootDir>/src/shared/verification/index',
    '^@providers/(.*)$': '<rootDir>/src/shared/providers/$1',
    '^@providers$': '<rootDir>/src/shared/providers/index',
    '^@templates/(.*)$': '<rootDir>/src/shared/templates/$1',
    '^@templates$': '<rootDir>/src/shared/templates/index',
    '^@errors/(.*)$': '<rootDir>/src/shared/errors/$1',
    '^@errors$': '<rootDir>/src/shared/errors/index',
    '^@types/(.*)$': '<rootDir>/src/shared/types/$1',
    '^@types$': '<rootDir>/src/shared/types/index',
  },
  collectCoverage: true,
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/modules/**/*.{controller,service,repository,transformer}.ts',
    '!src/modules/**/*.dto.ts',
    '!src/modules/**/*.types.ts',
    '!src/modules/**/index.ts',
    '!src/**/*.d.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 15,
      functions: 25,
      lines: 35,
      statements: 35,
    },
  },
  passWithNoTests: true,
  verbose: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};

module.exports = config;
