/* tslint:disable */
/* eslint-disable */
/**
 * Health AI - Smart Healthcare Monitoring Platform API
 * Production-grade OpenAPI 3.0.3 specification for the Health AI platform backend architecture. Provides RESTful endpoints for IoT sensor telemetry ingestion (ESP32), computer vision facial emotion recognition, Digital Twin physiological state modelling, real-time stress assessment, cardiovascular risk evaluation, AI chatbot interaction, automated clinical recommendations, and notification services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@healthai.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost:5000/api/v1".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {
}
