/* tslint:disable */
/* eslint-disable */
/**
 * Health AI - Smart Healthcare Monitoring Platform API
 * Production-grade OpenAPI 3.0.3 specification for the Health AI platform backend architecture. Provides RESTful endpoints for IoT sensor telemetry ingestion (ESP32), computer vision facial emotion recognition, Digital Twin physiological state modelling, real-time stress assessment, cardiovascular risk evaluation, AI chatbot interaction, automated clinical recommendations, and notification services. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@healthai.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

